### ISSUE TITLE
stringi dependency

### ISSUE THREAD

**Issue by jsta** [ropensci/rdryad#13]
When I execute `library(rdryad)` after installation I receive the following error message:

> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Error: package or namespace load failed for ‘rdryad’

Works fine after I run `install.packages("stringi")`.

**Comment by sckott** [comment]
Did you install from CRAN or from github?

**Comment by jsta** [comment]
CRAN

**Comment by sckott** [comment]
Likely due to `stringr` now depending on `stringi`, and we depend on `stringr` https://github.com/ropensci/rdryad/blob/master/DESCRIPTION#L23 I imagine you haven't updated `stringr` in a while? 

I opened a new milestone https://github.com/ropensci/rdryad/milestones/v0.2 - and I'll push to CRAN soon

**Comment by jsta** [comment]
I am running the latest `stringr` version 1.0.0. I installed on 5/22/2015.

**Comment by sckott** [comment]
Weird, I guess you would have already had `stringi` in that case. Not sure what happened then. Hopefully I can solve this with the new version

**Comment by sckott** [comment]
pushing a new version soon, `stringr` dropped
