### ISSUE TITLE
Arg for specifying target directory for files retrieved by dryad_download?

### ISSUE THREAD

**Issue by trashbirdecology** [ropensci/rdryad#34]
Maybe I am missing it, but suggest adding an argument in `dryad_download()` that allows user to specify the cache/file storage directory. For example, 
```r
mydir <- tempdir()
rdryad::dryad_download("10.5061/dryad.1nm650h", path=mydir)
```

**Comment by krzbar** [comment]
I would second this request, as it makes it impossible to comply with CRAN policies it seems
https://github.com/ropensci/rdryad/issues/35#issue-1048334902
Best wishes
Krzysztof Bartoszek

**Comment by mpadge** [comment]
@trashbirdecology @krzbar Thanks for opening the issues and helping to improve the package. Former maintainer @sckott has left rOpenSci, so I've taken over maintenance here now. PR #36 should go most of the way to fixing your concerns. It will likely still need a couple of tweaks, and most importantly some changes to documentation to demonstrate how to do this. Please let us know whether either of you might be interested in submitting a PR with improved documentation, basically by demonstrating the `reprex` given in #36. Thanks!

**Comment by krzbar** [comment]
@mpadge Thank you for the changes! At the moment I have removed the call to rdryad to stay on CRAN. However if the commit above will work and be on CRAN I will revert to calling rdryad::dryad_download() at the next iteration of mvSLOUCH. I will be happy to provide feedback, see what sort of documentation can be cooked up from that implementation when I will be working on this. However, at the moment I cannot unfortunately declare when this will be (due to tonnes of other academic obligations).
